<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Cache;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $img1 = 'assets/images/carwash.avif';
        $img2 = 'assets/images/car.avif';

        $products = [
            [
                'name'             => 'Premax Ceramic Detail Kit',
                'slug'             => 'premax-ceramic-detail-kit',
                'category'         => 'care_kits',
                'description'      => 'Studio-grade maintenance kit for coated vehicles. The same products our technicians use between ceramic coating services.',
                'long_description' => 'The Premax Ceramic Detail Kit contains everything you need to maintain a ceramic-coated vehicle between professional services. Formulated in partnership with our in-house detailers, each product is safe on all coatings — SiO2, graphene and traditional glass coatings alike. The quick-detailer leaves a slick hydrophobic layer; the foam shampoo is pH neutral so it won\'t strip the coating. Everything arrives in a branded studio tote.',
                'features'         => ['Studio-grade SiO2 quick-detailer (500 ml)', 'pH-neutral foam shampoo (1 L)', 'Microfibre drying towel (60 × 90 cm, 700 GSM)', 'Spray applicator pad for sealant top-up', 'Premax branded studio tote bag', 'Care guide printed on recycled card'],
                'gallery'          => [$img1, $img2],
                'price'            => 14500.00,
                'sale_price'       => 12500.00,
                'image'            => $img1,
                'is_featured'      => true,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 1,
            ],
            [
                'name'             => 'Italian Leather Key Pouch',
                'slug'             => 'italian-leather-key-pouch',
                'category'         => 'lifestyle',
                'description'      => 'Hand-stitched leather pouch for your key fob. Premax red contrast stitch.',
                'long_description' => 'Full-grain vegetable-tanned Italian leather, cut and hand-stitched in Nairobi. The pouch wraps your key fob in a single layer of leather with a press-stud closure — protecting the fob from scratches without adding unnecessary bulk. The Premax red contrast stitch is a quiet nod to the studio.',
                'features'         => ['Full-grain vegetable-tanned Italian leather', 'Hand-stitched Premax red contrast stitch', 'Brass press-stud closure', 'Fits BMW, Mercedes, Porsche, Audi and Range Rover key fobs', 'Arrives in branded tissue paper and ribbon'],
                'gallery'          => [$img2, $img1],
                'price'            => 8500.00,
                'sale_price'       => null,
                'image'            => $img2,
                'is_featured'      => true,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 2,
            ],
            [
                'name'             => 'Glove Box Tool Roll',
                'slug'             => 'glove-box-tool-roll',
                'category'         => 'lifestyle',
                'description'      => 'Roadside essentials in a hand-stitched leather roll. For peace of mind on every journey.',
                'long_description' => 'A discreet leather tool roll designed to live in your glove box. Includes a digital tyre gauge calibrated to 0.1 bar, a compact multitool, a tyre plug kit, a micro torch, and a Premax microfibre. Roll it up, stash it away, forget about it until you need it. Canvas outer with full-grain leather binding.',
                'features'         => ['Full-grain leather roll with canvas outer', 'Digital tyre gauge (0–10 bar, 0.1 bar resolution)', 'Compact 12-in-1 multitool', 'Tyre plug kit (10 plugs, reamer, insertion tool)', 'Micro torch (100 lm, USB-C rechargeable)', 'Premax microfibre cloth'],
                'gallery'          => [$img1, $img2],
                'price'            => 11500.00,
                'sale_price'       => null,
                'image'            => $img1,
                'is_featured'      => true,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 3,
            ],
            [
                'name'             => 'Leather Conditioning System',
                'slug'             => 'leather-conditioning-system',
                'category'         => 'care_kits',
                'description'      => 'Maintain factory-soft leather with our atelier-grade conditioning duo.',
                'long_description' => 'Two-product system for maintaining the suppleness and colour depth of fine automotive leather. The leather cleaner lifts grime and body oil without stripping the finish; the conditioner restores moisture and applies a UV-protective barrier that prevents cracking. Safe on perforated, aniline, semi-aniline and pigmented leathers.',
                'features'         => ['Leather Cleaner 250 ml — pH balanced, non-foaming', 'Leather Conditioner 250 ml — natural oils + UV inhibitor', 'Horsehair applicator brush', 'Microfibre applicator pad', 'Care instruction card', 'Suitable for all automotive leather grades'],
                'gallery'          => [$img2, $img1],
                'price'            => 6800.00,
                'sale_price'       => null,
                'image'            => $img2,
                'is_featured'      => false,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 4,
            ],
            [
                'name'             => 'Studio Microfibre Set',
                'slug'             => 'studio-microfibre-set',
                'category'         => 'accessories',
                'description'      => 'Six colour-coded workshop microfibres graded by the task. The ones our technicians use daily.',
                'long_description' => 'Six microfibres, each optimised for a specific detailing task. Colour-coded so you never contaminate surfaces: red for wheels, blue for glass, grey for interior, cream for paint and coating application, orange for drying, and white for final inspection. All 70/30 polyester/polyamide blend at 400 GSM minimum.',
                'features'         => ['6 microfibres, each colour-coded by task', '70/30 polyester-polyamide blend, 400–700 GSM', 'Edgeless design on paint-safe cloths', 'Twist-pile drying towel (700 GSM)', 'Machine washable at 40°C', 'Presented in a reusable mesh laundry bag'],
                'gallery'          => [$img1, $img2],
                'price'            => 4500.00,
                'sale_price'       => null,
                'image'            => $img1,
                'is_featured'      => false,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 5,
            ],
            [
                'name'             => 'Premax Snapback',
                'slug'             => 'premax-snapback',
                'category'         => 'apparel',
                'description'      => 'Studio-issue structured snapback in charcoal. White embroidered Premax wordmark.',
                'long_description' => 'The same cap worn in the studio. Structured six-panel in charcoal wool blend with a flat brim and snap closure. White embroidered Premax wordmark on the front panel, small red square on the rear. Unisex fit, adjustable from 54 to 62 cm.',
                'features'         => ['Structured six-panel, charcoal wool blend', 'Flat brim, snap closure (54–62 cm adjustable)', 'White embroidered Premax wordmark', 'Red square brand mark on rear', 'Tonal sweatband', 'Studio-issue — same cap worn by our technicians'],
                'gallery'          => [$img2, $img1],
                'price'            => 3500.00,
                'sale_price'       => null,
                'image'            => $img2,
                'is_featured'      => false,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 6,
            ],
            [
                'name'             => 'Long-Life Tyre Dressing',
                'slug'             => 'long-life-tyre-dressing',
                'category'         => 'care_kits',
                'description'      => 'Water-based tyre dressing that stays satin-black for weeks, not hours.',
                'long_description' => 'Most tyre dressings sling off the tyre onto your bodywork within a day. This water-based formula bonds to the rubber surface and stays put for 4–6 weeks, even in Nairobi rain. Applies with the included foam applicator pad and delivers a consistent satin sheen — not the greasy gloss of solvent-based dressings.',
                'features'         => ['Water-based — no slinging on bodywork', '4–6 week durability on properly prepared tyres', 'Satin finish (not high-gloss)', '500 ml trigger spray bottle', 'Foam applicator pad included', 'UV inhibitors prevent tyre browning'],
                'gallery'          => [$img1, $img2],
                'price'            => 2900.00,
                'sale_price'       => null,
                'image'            => $img1,
                'is_featured'      => false,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 7,
            ],
            [
                'name'             => 'Studio Detailing Brush Set',
                'slug'             => 'studio-detailing-brush-set',
                'category'         => 'accessories',
                'description'      => 'Five natural and synthetic brushes for interior and exterior detail work.',
                'long_description' => 'Five brushes, each sized and bristled for a specific detailing task. The boar hair interior brush is soft enough for piano black trim; the stiff nylon wheel brush reaches brake dust behind spokes; the crevice brush clears door shuts and rubber seals. Aluminium ferrules, anti-static handles.',
                'features'         => ['Boar hair interior detail brush (25 mm, ultra-soft)', 'Natural hair trim and vent brush (15 mm)', 'Synthetic crevice brush (10 mm, medium)', 'Nylon wheel spoke brush (stiff)', 'Long-reach lug nut brush', 'Anti-static handles, aluminium ferrules'],
                'gallery'          => [$img2, $img1],
                'price'            => 7200.00,
                'sale_price'       => null,
                'image'            => $img2,
                'is_featured'      => false,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 8,
            ],
            [
                'name'             => 'Premax Studio Holdall',
                'slug'             => 'premax-studio-holdall',
                'category'         => 'apparel',
                'description'      => 'Waxed canvas holdall with full-grain leather handles. Studio-grade durability.',
                'long_description' => 'A weekend-capable holdall in waxed canvas with full-grain leather grab handles and shoulder strap. Large main compartment with a removable internal divider; front slip pocket; YKK zips throughout. The Premax wordmark is debossed on the leather base patch. Develops character with use.',
                'features'         => ['Waxed canvas outer, full-grain leather trim', 'Full-grain leather grab handles and shoulder strap', 'Large main compartment with removable divider', 'YKK zips throughout', 'Premax wordmark debossed on leather base patch', 'Dimensions: 55 × 28 × 28 cm'],
                'gallery'          => [$img1, $img2],
                'price'            => 18500.00,
                'sale_price'       => null,
                'image'            => $img1,
                'is_featured'      => true,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 9,
            ],
            [
                'name'             => 'Clay Bar Decontamination Kit',
                'slug'             => 'clay-bar-decontamination-kit',
                'category'         => 'care_kits',
                'description'      => 'Professional-grade clay bar, lubricant and microfibre for a glass-smooth finish.',
                'long_description' => 'The same clay bar system used in our detailing bay. The medium-grade clay removes embedded iron fallout, industrial fallout and road grime that washing cannot. Paired with the synthetic clay lubricant to prevent marring. Leaves paint feeling genuinely smooth — run your fingers over it.',
                'features'         => ['200 g medium-grade detailing clay bar', 'Clay lubricant spray 500 ml (pH neutral)', 'Dedicated clay microfibre (400 GSM)', 'Clay storage container', 'Instruction card with technique guidance', 'Suitable for paint, glass, plastic trim and chrome'],
                'gallery'          => [$img2, $img1],
                'price'            => 5800.00,
                'sale_price'       => null,
                'image'            => $img2,
                'is_featured'      => false,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 10,
            ],
            [
                'name'             => 'Wheel Woolies Set',
                'slug'             => 'wheel-woolies-set',
                'category'         => 'accessories',
                'description'      => 'Three lambswool barrel brushes that reach every part of your alloys safely.',
                'long_description' => 'Lambswool barrel brushes in three sizes: 68 mm for barrel and face, 40 mm for spokes and lug nut pockets, 20 mm for centre caps and tightest areas. Flexible wire core bends to any angle. Safe on painted, polished, powder-coated and chrome wheels. The wool holds soapy water and releases it evenly without scratching.',
                'features'         => ['Three lambswool barrel brushes (68 mm / 40 mm / 20 mm)', 'Flexible wire core bends to any angle', 'Safe on all alloy finishes', 'Solid plastic handle with rubber grip', 'Machine washable lamb\'s wool', 'Presented in a resealable bag'],
                'gallery'          => [$img1, $img2],
                'price'            => 3200.00,
                'sale_price'       => null,
                'image'            => $img1,
                'is_featured'      => false,
                'is_sold_out'      => false,
                'is_active'        => true,
                'sort_order'       => 11,
            ],
            [
                'name'             => 'Premax Studio Tee',
                'slug'             => 'premax-studio-tee',
                'category'         => 'apparel',
                'description'      => 'Heavyweight 240 GSM cotton tee. The one worn in the studio.',
                'long_description' => 'The studio tee in 240 GSM combed ring-spun cotton. Slightly boxy fit — not fashion-relaxed, just correct. White Premax wordmark centred on chest; small red square on the left sleeve. Pre-washed to prevent shrinkage. Available in Charcoal, Black and Off-White.',
                'features'         => ['240 GSM combed ring-spun cotton', 'Pre-washed — true to size after washing', 'White Premax wordmark, chest centre', 'Red square brand mark, left sleeve', 'Available in Charcoal, Black, Off-White', 'Sizes XS–XXL'],
                'gallery'          => [$img2, $img1],
                'price'            => 2500.00,
                'sale_price'       => null,
                'image'            => $img2,
                'is_featured'      => false,
                'is_sold_out'      => true,
                'is_active'        => true,
                'sort_order'       => 12,
            ],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }

        Cache::forget('shop.products');

        $this->command->info('ProductSeeder: ' . count($products) . ' products seeded.');
    }
}
